### ISSUE TITLE
What is the format of train.txt and top_19_human_need_path.txt?

### ISSUE THREAD

**Issue by tanabehikari** [debjitpaul/Multi-Hop-Knowledge-Paths-Human-Needs#1]
Excuse me, would you tell me what "train.txt" in config.txt and "top_19_human_need_path.txt" in experiment.py contains?
I want to run your models, but now confusing these known files...

**Comment by debjitpaul** [comment]
Thank you for your interest. The format of the data can be found in the /src/data_prep directory. The sample of "train.txt" can be found in src/data_prep/sample_data_human_needs_reiss.txt and "top_19_human_need_path" is the knowledge paths which can be found in /src/data_prep/sample_human_need_paths.txt   

For the convenience, I also added the comments and added two more python script named experiment_reiss_without.py and Human_needs_elmo_without.py which is for running the neural models without the knowledge paths.

**Comment by tanabehikari** [comment]
Thank you for your quick reaction!
I will try to use these files, thank you.
