### ISSUE TITLE
About Requirements

### ISSUE THREAD

**Issue by victorup** [debjitpaul/Multi-Hop-Knowledge-Paths-Human-Needs#4]
Hello,
Which version of TensorFlow do you use?

**Comment by victorup** [comment]
And I get an error trying to run "elmo = hub.Module("https://tfhub.dev/google/elmo/2", trainable=True)":

tarfile.ReadError: unexpected end of data
During handling of the above exception, another exception occurred:
OSError: https://tfhub.dev/google/elmo/2 does not appear to be a valid module.

Do you know how to solve this problem？
Thanks！

**Comment by debjitpaul** [comment]
Tensorflow Version: 1.12.0

**Comment by victorup** [comment]
In your code,  I see the weights list as follow:
w = [3.929112469627414, 4.352634266669815, 4.105348968927056, 4.009469417408209, 4.436903109491611, 3.4714643441750805, 4.533726764493145, 3.665643259544512, 5.264175448882736, 6.026320782448594, 3.7522367243231805, 3.8019798963053515, 7.896001211803761, 8.024995943144209, 3.3076036095385644, 3.81662584588786, 8.618279130276653, 6.7344516295276895]
How did you get this weights?

**Comment by debjitpaul** [comment]
<img width="497" alt="Screenshot 2020-04-26 at 12 22 22" src="https://user-images.githubusercontent.com/14016296/80304796-af1f0780-87b8-11ea-8d3b-36f137b7531d.png">
I would request you to read the paper. It is clearly mentioned that w is the weight distribution learned from the training data.

**Comment by victorup** [comment]
Thank you for your answer!
I don't know how to predict "Plutchik" category?
